### ISSUE TITLE
Selections are hard to see / do not contrast enough

### ISSUE THREAD

**Issue by MvEerd** [Jmorjsm/rose-pine-intellij#14]
Selections in rose-pine and rose-pine-moon are quite difficult to see on my monitors, especially when paired with the color that the currently selected line has;
![image](https://user-images.githubusercontent.com/12560315/233313701-a25ee94b-45d9-42d8-87df-3d12b8c86b9f.png)
![image](https://user-images.githubusercontent.com/12560315/233314172-495d4a84-8a8b-49ff-aecb-0d086e0d2b0d.png)

In the examples only `setError` is highlighted

**Comment by jonmorgs** [comment]
resolved by #18
