### ISSUE TITLE
Support for CLion Nova

### ISSUE THREAD

**Issue by Andreeew369** [Jmorjsm/rose-pine-intellij#24]
I dont know if this counts as an issue but will there be a support for the new CLion Nova IDE? It says that this theme doesnt support the new version.

**Comment by jonmorgs** [comment]
Hi! It looks like CLion Nova is the preview version of CLion. This should be resolved in version 0.0.9 which is currently being verified for release by JetBrains. When the update is available, which should be in the next couple of days, could you confirm whether this resolves your issue?

**Comment by jonmorgs** [comment]
@Andreeew369 In the meantime, you could also try out [0.1.0 from the preview channel](https://plugins.jetbrains.com/plugin/18141-ros-pine/versions/preview). This shouldn't have an upper boundary for IDE version compatibility.

**Comment by Andreeew369** [comment]
It works now. Thanks
