### ISSUE TITLE
Not working on IntelliJ IDEA 2022.2.1

### ISSUE THREAD

**Issue by isolume** [Jmorjsm/rose-pine-intellij#6]
![image](https://user-images.githubusercontent.com/57784409/186031753-c31e4d1f-c233-4fef-b4f9-770c4eb4813e.png)
I get this while viewing the page, and it does not show up on IntelliJ Idea.

**Comment by jonmorgs** [comment]
Should be resolved by #5, the updated version is awaiting approval on JetBrains Marketplace now.
